### ISSUE TITLE
any doc

### ISSUE THREAD

**Issue by diadal** [lessmore92/php-ripple-address-codec#1]
no doc

**Comment by lessmore92** [comment]
This class full ported from JS version,
[Original Doc](https://github.com/ripple/ripple-address-codec) is a good reference.

But for using, after install using composer:
```BASH
composer require lessmore92/php-ripple-address-codec
```

Use the class(es) and access to all available methods.

```PHP
require_once "vendor/autoload.php";

$api = new \Lessmore92\RippleAddressCodec\RippleAddressCodec();
echo $api->classicAddressToXAddress("rGWrZyQqhTp9Xu7G5Pkayo7bXjH4k4QYpf", 4294967295);
```
