### ISSUE TITLE
Feeding an X address to isValidClassicAddress() results in crash

### ISSUE THREAD

**Issue by quakemmo** [lessmore92/php-ripple-address-codec#3]
```PHP Fatal error:  Uncaught TypeError: Lessmore92\RippleAddressCodec\CodecWithXrpAlphabet::decode(): Return value must be of type array, none returned in /<stripped>/ripple/vendor/lessmore92/php-ripple-address-codec/src/CodecWithXrpAlphabet.php:100```

This happens when I feed a valid X addess codec to isValidClassicAddress().

**Comment by lessmore92** [comment]
Please show X address that make exception

**Comment by quakemmo** [comment]
```T7gVzABcQ9Wn5fhf6Kd56Xj2xiLjgJRiRWWSFZ6zNncLGqh```
Generated with classicAddressToXAddress() out of a regular testnet XRP address ```raMByQGTYwtmtFWiMCXRsK8xAWWJqUXEtb```

**Comment by lessmore92** [comment]
Thanks for reporting this issue.
Fixed in the new release (**v1.0.3**)
Please upgrade your installation to a newer version to solve your problem.

**Comment by quakemmo** [comment]
Thanks for fixing this.
I added an issue to your Base-X repository as well.
