### ISSUE TITLE
Implicit conversion from float ... to int loses precision

### ISSUE THREAD

**Issue by most08** [lessmore92/php-ripple-address-codec#4]
When calling Sign::signWithKeypair() under PHP 8.1 the following error is occuring:

`Implicit conversion from float 25.164171604901235 to int loses precision`.

The error occures in `vendor/lessmore92/base-x/src/BaseX.php`.

You have already fixed this issue in lessmore92/base-x in v1.0.4: https://github.com/lessmore92/base-x/commit/62a9cf3d26e2735cf749d79643075b4d39df8d3f

But the [composer-package](https://github.com/lessmore92/php-ripple-address-codec/blob/main/composer.json) of lessmore92/php-ripple-address-codec in v1.0.3 is still using requiring the pinned version v1.0.3 of lessmore92/base-x rather than v1.0.4.
Can you please change the requirements of the lessmore92/php-ripple-address-codec?
Thanks in advance.

**Comment by lessmore92** [comment]
It's done.
